name: Deploy Playground

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.1.0

      - uses: actions/checkout@v6.1.0
        with:
          repository: vuejs/blog
          path: 'vuejsblog'
          sparse-checkout: posts

      # clone https://github.com/vuejs/blog
      - run: |
          mkdir -p playground/docs/posts
          cp -r vuejsblog/posts/. playground/docs/posts/

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.1.0
        with:
          cache: true

      - name: Setup Node
        uses: actions/setup-node@v6.5.0
        with:
          node-version: 22

      - name: Setup Pages
        uses: actions/configure-pages@v6.0.0
        with:
          enablement: true

      - name: Install Dependency
        run: pnpm install

      - name: Build Dist
        run: pnpm build

      - uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: playground/.vitepress/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5.0.0
